config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'projects#index'
  get 'work/:slug', to: 'projects#show', as: :project

  get 'about', to: 'pages#about'
  get 'resume', to: 'pages#resume'
  get 'pdf', to: 'pages#pdf'

  get 'blog', to: 'posts#index'
  get 'blog/:slug', to: 'posts#show', as: :post
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, :content, presence: true

  scope :ordered, -> do
    order created_at: :desc
  end

  scope :published, -> { ordered.where(published: true) }

  before_create :set_slug

  private

  def set_slug
    self.slug = self.title.parameterize
  end
end

app/models/project.rb
class Project < ApplicationRecord

  validates :name, :summary, :content, :priority_order, :image, presence: true

  mount_uploader :image, ProjectImageUploader

  scope :ordered, -> do
    order :priority_order
  end

  scope :published, -> { ordered.where(published: true) }

  before_create :set_slug

  private

  def set_slug
    self.slug = self.name.parameterize
  end
end

app/models/redactor_rails/asset.rb
class RedactorRails::Asset < ActiveRecord::Base
  include RedactorRails::Orm::ActiveRecord::AssetBase
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  validates_presence_of :data
end

app/models/redactor_rails/document.rb
class RedactorRails::Document < RedactorRails::Asset
  mount_uploader :data, RedactorRailsDocumentUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end

  def as_json_methods
    [:image]
  end
end

app/models/redactor_rails/picture.rb
class RedactorRails::Picture < RedactorRails::Asset
  mount_uploader :data, RedactorRailsPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def pdf
    pdf = Rails.root.join('public/pdf/noe-stauffert.pdf')
    send_file(pdf, filename: 'noe-stauffert.pdf', type: 'application/pdf', disposition: :inline)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.published
  end

  def show
    @post = Post.find_by_slug(params[:slug])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.published
  end

  def show
    @project = Project.find_by_slug(params[:slug])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(text)
    content_for :title, text
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = if content_for?(:title) then yield(:title) + ' | '
      | Noe Stauffert
    = csrf_meta_tags
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    = stylesheet_link_tag    'application', media: 'all'

  body class="#{controller_name} #{action_name} bg-grey"
    .container-fluid
      .row
        .col-md-10.col-md-offset-1
          = render 'shared/navbar'
          = render 'shared/notifications'
          = yield
          = render 'shared/footer'
    = javascript_include_tag 'application'

app/views/pages/about.html.slim
- title("About")
.row.padded-top
  .col-sm-3
    img.img-responsive.center-block src="https://avatars2.githubusercontent.com/u/10394006?v=3&s=460"
  .col-sm-9.justify
    p
      | Most recently I worked at #{link_to "Capsens", "http://capsens.eu/", target: :blank}, a startup based in Paris which builds crowdfunding platforms for clients. Have a look at some of the projects I worked on: #{link_to "Ekosea", "https://ekosea.com/", target: :blank}, #{link_to "Suncities", "https://suncities.net/", target: :blank} and #{link_to "HappyJ", "https://happyj.fr/", target: :blank}.
    p
      ' I found my way to web development through
      a href="https://www.lewagon.com/" target="_blank" Le Wagon
      ', a developer bootcamp in Paris. This 9-week intensive program is where I learned Ruby on Rails through hands-on exercises and pair-programming. The course culminated in a capstone project where I was part of a team of 3 who built a marketplace prototype for high-end furniture,
      a href="https://lesalon.herokuapp.com" target="_blank" Le Salon
      |.
    p
      | Prior to being a web developer, I was a scuba diving instructor and I spent several years in South East Asia, where I taught myself Indonesian and Malay. I learned how to take apart regulators. A regulator is a diver’s life support underwater, and I loved the confidence I got from knowing that my being meticulous in the rebuilding process is what ensured everyone's safety. Just like I love knowing that an app I built can be reliably deployed because of the tests I wrote.
      br
      | I left my native country of France for Asia after obtaining a Master's degree in Translation. My love of languages has extended beyond natural languages to programming languages. I instantly found programming fascinating and loved that a computer does exactly what you tell it to. So different from what I was used to with natural languages! I had discovered a passion for figuring out how things work while I worked in the diving industry, and I found it even more exciting in the computer realm.

app/views/pages/resume.html.slim
object data=pdf_path type="application/pdf" style="width: 100%; height: 1200px; padding-top: 1em"
  a href=pdf_path noe-stauffert.pdf

app/views/posts/index.html.slim
- title("Blog")
.row
  - @posts.each do |post|
    .col-xs-12.bottom-lined
      a href=post_path(post.slug)
        h3 =post.title
        span =post.created_at.strftime('%B %e, %Y')
      .redact
        p =raw(post.content.truncate(400))
      hr

app/views/posts/show.html.slim
- title(@post.title)
h2 =@post.title
p = @post.created_at.strftime('%B %e, %Y')
.redact
  =raw(@post.content)
=link_to "Back to blog index", blog_path

app/views/projects/index.html.slim
.row
  h2 Hi, I'm No&eacute;. I'm a Rails developer. Check out some of my projects:
  .padded-top
    - @projects.each do |project|
      .col-md-4
        .col-xs-12
          a href=project_path(project.slug)
            img.padded-bottom.img-responsive.center-block src=project.image.content
            h3 =project.name
        .col-xs-12.bottom-lined
          .redact
            p =raw(project.summary)
          hr

app/views/projects/show.html.slim
- title(@project.name)
h2 =@project.name
.redact
  =raw(@project.content)
=link_to "Back to projects", root_path

app/views/shared/_footer.slim
.footer
  ul.list-inline.pull-right
    li
      a href="https://www.linkedin.com/in/noestauffert" target="_blank"
        i.fa.fa-linkedin aria-hidden="true"
    li
      a href="https://github.com/nozbzh" target="_blank"
        i.fa.fa-github aria-hidden="true"
    li
      a href="https://twitter.com/@nozbzh" target="_blank"
        i.fa.fa-twitter aria-hidden="true"

app/views/shared/_navbar.html.slim
nav.navbar.navbar-default.navbar-wagon.neg-margin role="navigation"
  /! Brand and toggle get grouped for better mobile display
  .row
    .col-xs-9.col-sm-5.no-hover
      a href=root_path
        h1 NOE STAUFFERT
        p
          | Web developer
    .col-xs-3.col-sm-7
      .navbar-header
        button.navbar-toggle.collapsed data-target="#navbar-menu" data-toggle="collapse" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
      /! Collect the nav links, forms, and other content for toggling
      #navbar-menu.collapse.navbar-collapse
        ul.nav.navbar-nav.navbar-right.sticky-bottom
          li class="#{controller_name == 'projects' ? 'current' : ''}"
            =link_to "work", root_path
          li class="#{action_name == 'about' ? 'current' : ''}"
            =link_to "about", about_path
          li class="#{action_name == 'resume' ? 'current' : ''}"
            =link_to "resume", resume_path
          li
            a href="https://github.com/nozbzh" target="_blank" github
          li class="#{controller_name == 'posts' ? 'current' : ''}"
            =link_to "blog", blog_path

app/views/shared/_notifications.slim
- if (message = flash[:notice]).present?
  .container-fluid.alert.alert-notice style='padding: 20px;'
    button.close aria-label="Close" data-dismiss="alert" type="button"
      span aria-hidden="true" ×
    center: span= message.html_safe

- if (message = flash[:error]).present?
  .container-fluid.alert.alert-error style='padding: 20px;'
    button.close aria-label="Close" data-dismiss="alert" type="button"
      span aria-hidden="true" ×
    center: span= message.html_safe

- if (message = flash[:alert]).present?
  .container-fluid.alert.alert-alert style='padding: 20px;'
    button.close aria-label="Close" data-dismiss="alert" type="button"
      span aria-hidden="true" ×
    center: span= message.html_safe

- if (message = flash[:success]).present?
  .container-fluid.alert.alert-success style='padding: 20px;'
    button.close aria-label="Close" data-dismiss="alert" type="button"
      span aria-hidden="true" ×
    center: span= message.html_safe

- [:notice, :error, :alert, :success].each do |name|
  - flash[name] = nil